# Generated by Django 5.2.5 on 2025-09-04 09:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_remove_submission_grade_remove_submission_graded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='feedback',
            new_name='text_answer',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.AddField(
            model_name='assignment',
            name='target_group',
            field=models.CharField(choices=[('all', 'All Students'), ('my_students', 'Only My Students')], default='my_students', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
