# Generated by Django 5.2.5 on 2025-09-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='status',
        ),
        migrations.AddField(
            model_name='query',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
