# Generated by Django 5.2.5 on 2025-09-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_remove_query_status_query_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='responded_at',
            new_name='replied_at',
        ),
        migrations.RemoveField(
            model_name='query',
            name='response',
        ),
        migrations.AlterField(
            model_name='query',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
