# Generated by Django 4.1.5 on 2025-09-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_score',
            field=models.FloatField(default=0.0),
        ),
    ]
