# Generated by Django 5.1.4 on 2025-10-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0015_submission_ai_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='project_reports/'),
        ),
    ]
